# Model Configuration for 3H Disease Risk Prediction

# Interpretable Models
interpretable_models:
  logistic_regression:
    solver: 'liblinear'
    max_iter: 1000
    random_state: 42
    
  decision_tree:
    max_depth: 10
    min_samples_split: 20
    min_samples_leaf: 10
    random_state: 42

# Black-box Models
blackbox_models:
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 10
    random_state: 42
    
  svm:
    C: 1.0
    kernel: 'rbf'
    gamma: 'scale'
    random_state: 42
    
  neural_network:
    hidden_layers: [64, 32, 16]
    activation: 'relu'
    optimizer: 'adam'
    learning_rate: 0.001
    epochs: 100
    batch_size: 32

# Cross Validation
cv:
  n_folds: 5
  shuffle: true
  random_state: 42

# Evaluation Metrics
metrics:
  - 'accuracy'
  - 'precision'
  - 'recall'
  - 'f1'
  - 'roc_auc'